backend/build.gradle

> ex) #4 
> MongoDB에서 PostgreSQL로 DB 변경
>
> Application-*.yml 변경 부분 노션에서 참고해주세요~

chore: MongoDB에서 PostgreSQL로 DB 변경

---

.github/workflows/gpt-ci-cd.yml
gpt/Dockerfile
gpt/docker-compose.yml

> #20 
- Docker 파일 생성
- docker-compose 파일 생성
- gpt-ci-cd.yml workflow 추가
>

GPT Server Docker 배포 및 GitHub Actions CI/CD 구축

---

gpt/config.py
gpt/main.py
gpt/routes/gpt.py
gpt/utils/logging.py
gpt/utils/mindmap.py

> #25 
- 로깅 코드 분리 후 utils 패키지로 이동
- 마인드맵 파싱 기능 분리 후 utils 패키지로 이동
- 불필요한 ```print``` 코드 삭제
- React localhost:3000 cors 설정
- CORS ORIGINS .env로 이동
>

GPT Server 코드 리팩터링 및 구조 변경 

---

frontend/eslint.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/api/client.ts
frontend/src/api/endpoints.ts
frontend/src/hooks/queries/useMindmap.ts
frontend/src/root.tsx
frontend/src/services/mindmapService.ts
frontend/src/types/api/mindmap/index.ts
frontend/src/types/api/mindmap/request.ts
frontend/src/types/api/mindmap/response.ts

resolve #28 
API 통신을 위한 기본 구조를 설계하고 구현했습니다.
백엔드 서버와 GPT 서버를 위한 별도의 API 클라이언트를 axios 구성했으며, 타입 시스템, 서비스 레이어, 그리고 React Query 훅을 포함한 종합적인 API 통신 아키텍처를 개발했습니다. 
현재 GPT API 관련된 API가 개발되어 있는 상태라, 해당 API를 예시로 구조를 잡아놨습니다!
- **TanStack Query 라이브러리 설치**
- `@tanstack/react-query` 및 관련 패키지들을 프로젝트에 추가
- Query Client 초기 설정 구성
- **ESLint 설정**
- `@tanstack/eslint-plugin-query` 플러그인 활용하여 TanStack Query 권장 규칙 전체 적용
- **개발 도구(DevTools) 설정**
- [TanStack Query의 DevTools](https://tanstack.com/query/latest/docs/framework/react/devtools) 추가
오른쪽 아래에 다음과 같은 아이콘이 있는데 누르면, Tanstack Query Dev Tool 활성화됩니다!
`@/api/client.ts`
저희가 GPT 서버와, 백엔드 서버가 각각 존재하므로 별도의 Axios 인스턴스를 생성해줬습니다. 각 인스턴스에 대한 인터셉서는 추후에 인증/인가 로직이 결정되면 이에 맞게 수정하도록 합시다!
`@/api/endpoints.ts`
API 앤드포인트를 해당 파일에서 상수로 관리합니다. 변수 이름은 백엔드 측에서 설정한 API URL의 네이밍에 맞춰 …

TanStack Query 라이브러리 설치 및 API 호출 구조 모듈화 #28

---

.github/workflows/backend-ci-cd.yml
backend/docker-compose.yml

> ex) #4
> docker-compose.yml 문법 오류 수정 & ci-cd.yml 에서 환경 변수 적용
>

fix: docker-compose.yml 문법 오류 수정 & ci-cd.yml 에서 환경 변수 적용

---

.github/workflows/backend-ci-cd.yml
backend/docker-compose.yml

> ex) #4 
> Docker Image version을 latest tag로 변경
>

fix: Docker Image를 latest 버전으로 변경

---

.github/workflows/backend-ci-cd.yml

Test: CI/CD를 위한 Test 진행 (코드 변경 사항 x)

---

.github/workflows/backend-ci-cd.yml

> ex) #4 
> ci-cd 환경변수 설정 기능 추가
>

chore: ci-cd 환경변수 설정 기능 추가

---

backend/src/main/java/capstone/backend/global/redis/RedisConfig.java

> ex) #4 
> memory leak 방지를 위한 redisConnectionFactory 제거 로직 추가
>

feat: memory leak 방지를 위한 redisConnectionFactory 제거 로직 추가

---

.github/workflows/backend-ci-cd.yml
backend/docker-compose.yml

> ex) #4 
> docker-compose.yml에 들어가는 환경변수 제거
>

fix: docker-compose.yml에 들어가는 환경변수 제거

---

backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java

> #51
예외 처리 시 ID 파라미터를 제거하였습니다.
>

refactor: 마인드맵 예외 처리 시 ID 파라미터 제거

---

backend/src/main/java/capstone/backend/BackendApplication.java
backend/src/main/java/capstone/backend/domain/eisenhower/batch/NotificationJobConfig.java
backend/src/main/java/capstone/backend/domain/eisenhower/batch/step/DeleteOldNotificationsTasklet.java
backend/src/main/java/capstone/backend/domain/eisenhower/batch/step/GenerateNotificationTasklet.java
backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerItemController.java
backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerNotificationController.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/response/EisenhowerNotificationResponse.java
backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerNotification.java
backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerNotificationRepository.java
backend/src/main/java/capstone/backend/domain/eisenhower/scheduler/EisenhowerNotificationScheduler.java
backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerItemService.java
backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerNotificationService.java

- #97
- 아이젠하워 작업 검색 로직 및 API 구현
- 아이젠하워 알림 엔티티 작성 및 조회, 스케쥴러를 통한 알림 생성/삭제 구현(매일 06:00)
- 스케쥴러를 처음 써보는데 혹시 문제가 되는 부분이 있다면 뜨거운 리뷰 부탁드립니다!

[BE] feat: 아이젠하워 검색, 알림 기능 구현

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/reactFlow/FlowWrapper.tsx
frontend/src/components/reactFlow/nodes/ui/AnswerInputNode.tsx
frontend/src/components/reactFlow/nodes/ui/QuestionListNode.tsx
frontend/src/components/reactFlow/nodes/ui/RootNode.tsx
frontend/src/components/reactFlow/nodes/ui/SummaryNode.tsx
frontend/src/components/reactFlow/ui/NodeSelectionPanel.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Input.tsx
frontend/src/components/ui/Modal/AddPomodoro.tsx
frontend/src/components/ui/Modal/DeletePomodoro.tsx
frontend/src/components/ui/Modal/EndPomodoro.tsx
frontend/src/components/ui/MultiSlider.tsx
frontend/src/components/ui/SubSidebarAccordion.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/header/Header.tsx
frontend/src/components/ui/pomodoro/PomodoroItem.tsx
frontend/src/components/ui/pomodoro/PomodoroResult.tsx
frontend/src/components/ui/pomodoro/PomodoroTimer.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/CommonSubSidebarWrapper.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapAddButton.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapSubSidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/pomodoro/PomodoroSubSidebar.tsx
frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/mindmap.tsx
frontend/src/pages/pomodoro.tsx
frontend/src/styles/index.css

#121 
마인드맵 각 노드와, 관련 모달 스타일링을 수정했습니다.
해당 경우 해결 부탁드려요!
그리고 가능하면 질문 노드랑, 답변 노드 사이즈를 조금 키우고 싶어요! 확인 부탁드려요:)

[FE] style: 마인드맵 스타일링 수정

---

.github/workflows/backend-ci-cd.yml
backend/build.gradle
backend/logback.xml
backend/src/main/java/capstone/backend/global/property/AwsProperty.java
backend/src/main/resources/application.yml

- Closes #120 
- IAM User Role 추가
- application-aws.yml 추가
- cloudwatch 로깅을 위한 Logback.xml 코드 추가
- CI/CD 워크 플로우 추가
>

[BE] chore: cloudwatch 로그 수집 코드 작성

---

frontend/src/components/eisenhower/FilterBar.tsx
frontend/src/components/eisenhower/TaskDetailSidebar.tsx
frontend/src/components/eisenhower/view/PriorityView.tsx
frontend/src/components/ui/Modal/AddPomodoro.tsx
frontend/src/components/ui/Modal/DeletePomodoro.tsx

[FE] style : TaskCard 빈 부분 추가

---

frontend/src/components/ui/Modal/AddPomodoro.tsx
frontend/src/components/ui/Modal/EndPomodoro.tsx

[FE] fix: 뽀모도로 수정

---

backend/src/main/java/capstone/backend/global/property/CorsProperty.java
backend/src/main/java/capstone/backend/global/security/SecurityConfig.java

- Closes #139 
CORS 설정 중 setAllowCredential과 setAllowOriginPattern('*') 과의 충돌 이슈 해결
와일드카드 `*`를 배제하고 정확한 origin 네임 설정
`application-config.yml` 수정했으니 반영하겠습니다~

fix: CORS 에러 해결

---

backend/logback-spring.xml

- Closes #120 
active 모드에 따른 cloudwatch 로그 출력 제어
>

fix: logback-spring.xml 코드 수정 및 로깅 테스트

---

backend/src/main/java/capstone/backend/domain/mindmap/entity/Measured.java
backend/src/main/java/capstone/backend/domain/mindmap/entity/Node.java
backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java

- Closes #145 
> Measured 기본값 설정
Measured가 null인 경우 기본값으로 초기화하는 로직을 도입

[BE] refact: measured 필드 null 방지

---

.github/workflows/backend-ci-cd.yml

[BE] fix: ci-cd.yml 들여쓰기 수정

---

.github/workflows/backend-ci-cd.yml

fix: docker 명령어 수정

---

backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapResponse.java

- Closes #152 
> NodeResponse에 NodeData 포함하도록 구조 변경

refact: NodeResponse에 NodeData 포함하도록 구조 변경

---

backend/src/main/java/capstone/backend/global/security/SecurityConfig.java

- Closes #155 
PUT을 CORS 허용 메서드에 추가
>

hotfix: PUT Cors 요청 허용

---

backend/src/main/java/capstone/backend/domain/pomodoro/controller/PomodoroController.java
backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/PomodoroDTO.java
backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java

feat: 뽀모도로 생성 시 ID 값 반환 로직 추가

---

backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java

- Closes #180 
마인드맵 API를 V1으로 분기 처리했습니다.

refact: 사용하지 않는 마인드맵 API V1으로 분기 처리

---

backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
backend/src/main/java/capstone/backend/domain/bubble/dto/request/BubbleUpdateRequest.java
backend/src/main/java/capstone/backend/domain/bubble/entity/Bubble.java
backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemCreateRequest.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/response/EisenhowerItemResponse.java
backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
backend/src/main/java/capstone/backend/domain/eisenhower/scheduler/EisenhowerNotificationScheduler.java
backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskItemService.java

- Closes #204 
- 아이젠하워 수정 응답 DTO 필드명 수정
- 오늘의할일 어제할일 조회 API 오류 수정
- 아이젠하워 생성 API DTO에 memo 추가
- 버블 수정 기능 구현
- Swagger에 pathVariable 안뜨는 문제 해결
- 아이젠하워 알림 기능 00시 기준으로 변경
- 오늘의할일 00시 기준으로 변경
>

[BE] fix: 프론트 요청 사항 반영하여 코드 수정 작업

---

backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java

- Closes #207 
- 아이젠하워 작업 카테고리와의 연관관계 다대일로 변경
>

[BE] fix: 아이젠하워 작업 category 연관관계 오류 수정 

---

frontend/src/components/today/TodayMainDashborad.tsx
frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/today.tsx

resolve #217 
오늘의 할 일 페이지에서 반응형 깨지는 부분 수정했습니다!

[FE]: 오늘의 할 일 페이지 반응형 수정

---

frontend/src/components/ui/header/Header.tsx
frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/brainstorming.tsx
frontend/src/types/brainstorming.ts

#205
브레인스토밍 리팩토링 했습니다!
레이아웃 적용되면서 안맞던 부분 수정했습니다.
버블 배치 관련 코드 정돈 + 배치 고도화 진행했습니다~!
더 자잘한 부분은 추후에 수정하겠습니다~!
레이아웃 조금 건드려서 다른 부분 깨졌을지도..확인 한 번씩 해보세요

[FE] Feat : 205 brainstorming refactor

---

backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryFolderController.java
backend/src/main/java/capstone/backend/domain/inventory/service/InventoryFolderService.java

Closes #226 
> 폴더 상세 조회 API를 구현했습니다.

[BE] feat: 폴더 상세 조회 API 구현

---

frontend/src/api/endpoints.ts
frontend/src/components/today/PomodoroCard.tsx
frontend/src/components/today/TodayList.tsx
frontend/src/hooks/queries/pomodoro/usePatchPomodoro.ts
frontend/src/services/pomodoroService.ts
frontend/src/store/pomodoro.ts
frontend/src/types/api/pomodoro/index.ts
frontend/src/types/api/pomodoro/request.ts
frontend/src/types/pomodoro.ts

#233
뽀모도로 기록 저장을 위한 api 연결
다음과 같은 경우에 동작합니다.
1. 중지(가운데 버튼)
2. 중단(오른쪽 버튼 : reset)
3. 삭제 (x버튼)
4. 실행 중 다른 투두의 뽀모도로 실행하기 클릭
api 이렇게 쓰는게 맞는 지 모르는데 일단 함. 아니면 백엔드가 고치세요...ㅎ
딱히 기록되었다거나 하는 알림은 없는데 괜찮을지요

[FE] feat: 뽀모도로 api 연결

---

backend/src/main/java/capstone/backend/domain/pomodoro/exception/PomodoroDurationException.java
backend/src/main/java/capstone/backend/global/security/jwt/JwtAuthenticationFilter.java

- Closes #230 
swagger에 jwt 인증 필터를 거치게 되어 접근이 되지 않는 현상 발생
따라서, jwt 인증 필터의 조건문 로직을 수정함.
>

[BE] hotfix: Swagger에 접근이 되지 않는 문제 해결

---

frontend/package-lock.json
frontend/package.json
frontend/src/api/endpoints.ts
frontend/src/components/eisenhower/TaskModal.tsx
frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/eisenhower/view/PriorityView.tsx
frontend/src/components/today/TodayMainDashborad.tsx
frontend/src/components/ui/Modal/EisenhowerAi.tsx
frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts
frontend/src/layouts/DefaultLayout.tsx
frontend/src/services/eisenhowerService.ts
frontend/src/services/todayService.ts

> ex) #244 
아이젠하워에서 우선순위 사분면 AI 추천 api 와 아이젠하워 할 일 카드 오늘의 할 일로 내보내기 api 를 연결하였습니다.
우선순위 추천 api 호출을 화면 새로고침 했을 때 한 번에 하고 있는데 현재 컴포넌트 구조가 꼬여서 생긴 일 같습니다. 일단 TaskCard 상세도 새로고침 했을 때 조회되는 점은 고쳤고, 배포 후 코드 리팩토링 하면서 수정하겠습니다.

아이젠하워 추가 API 연동

---

frontend/src/api/endpoints.ts
frontend/src/components/today/TodayMainDashborad.tsx
frontend/src/components/ui/chart/PomodoroCompletionChar.tsx
frontend/src/hooks/queries/analysis/useGetPomodoroAnalysis.ts
frontend/src/hooks/queries/analysis/useGetTodayTaskAnalysis.ts
frontend/src/layouts/DefaultLayout.tsx
frontend/src/services/analysisService.ts
frontend/src/types/analysis.ts
frontend/src/types/api/analysis/response.ts

resolve #251 
뽀모도로 분석 API 연동 및 사이드바 레이아웃 반영안되는 문제 수정했습니다!

뽀모도로 분석 API 연동

---

frontend/src/api/endpoints.ts
frontend/src/components/ui/brainstorming/MoveToInventoryModal.tsx
frontend/src/hooks/queries/inventory/item/useCreateInventoryItem.ts
frontend/src/services/inventoryItemService.ts

resolve #253 
백엔드 요청 사항에 맞게 브레인스토밍 -> 보관함 관련 API 엔드포인트를 수정하였습니다

[FE]: 브레인스토밍 -> 보관함 API 수정

---

frontend/src/assets/q1.svg
frontend/src/assets/q2.svg
frontend/src/assets/q3.svg
frontend/src/assets/q4.svg
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Modal/NodeTaskModal.tsx
frontend/src/components/ui/Tabs.tsx
frontend/src/hooks/queries/brainstorming/useCreateMatrix.ts
frontend/src/pages/brainstorming.tsx
frontend/src/services/brainstormingService.ts
frontend/src/types/api/brainstorming/request.ts

> ex) #259 
버블 내용을 바탕으로 매트릭스를 클릭했을 때 새로운 할 일을 생성하도록 했습니다.
제목의 경우 버블 내용을 placeholder 로 두고 사용자가 작성할 수 있도록 처리했습니다. 
컴포넌트 최대한 활용하였고, api 도 다른 코드 참고해서 작성해보았습니다...! 그래서 크게 구조를 잘못 작성한 건 없?을? 없을 거예요...!

nodeTaskModal 디자인 수정 및 api 연결

---

frontend/src/components/ui/Dialog.tsx
frontend/src/pages/brainstorming.tsx

브레인스토밍 오류 수정
급해서 여기다 해서 올림
모달 스타일링 수정
브레인스토밍 오류 수정

[FE] feat: 브레인스토밍 오류 수정

---

frontend/src/components/ui/sidebar/Sidebar.tsx

resolve #275 
사이드바 활성화 버그를 수정했습니다.

[hotfix]: 사이드바 활성화 로직 수정

---

frontend/src/assets/arrow_left.svg
frontend/src/components/inventory/InventoryItemCard.tsx
frontend/src/components/inventory/modal/CreateFolderMoal.tsx
frontend/src/components/inventory/modal/DeleteFolderMoal.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/brainstorming/MoveToInventoryModal.tsx
frontend/src/components/ui/header/Header.tsx
frontend/src/pages/inventory.tsx
frontend/src/pages/inventoryDetail.tsx

헤더 로고 오늘의 할 일로 이동
#265
보관함 스타일링 수정
추가사항은 유찬님에게 부탁..!

[FE] feat: 보관함 스타일링 및 동작 수정

---

frontend/src/pages/brainstorming.tsx

#279 
plceholder 변경
placeholder ellipsis
중복 생성 동작 제한

[FE] fix: 브레인스토밍 수정

---

frontend/src/components/inventory/InventoryItemCard.tsx
frontend/src/components/inventory/modal/CreateFolderMoal.tsx
frontend/src/components/ui/header/Header.tsx
frontend/src/pages/inventory.tsx
frontend/src/pages/inventoryDetail.tsx
frontend/src/types/inventory.ts

resolve #278 
- 폴더 명,item명 ellipsis
- 디폴트 폴더 처리
- 보관함 아이템 편집모드 UI 수정
- 폴더 이름 10글자 미만으로 생성&수정되도록 처리

[FE] qa: 보관함 수정사항 반영

---

frontend/src/components/today/TodayList.tsx
frontend/src/components/ui/chart/DailyCompletionChart.tsx
frontend/src/components/ui/chart/PomodoroCompletionChart.tsx
frontend/src/components/ui/chart/TodayCompleteChart.tsx

[FE] qa 반영

---

frontend/src/components/today/ReminderList.tsx
frontend/src/components/today/TodayList.tsx
frontend/src/layouts/DefaultLayout.tsx
frontend/src/styles/index.css

[FE] QA 추가 반영

---

frontend/src/components/eisenhower/TaskModal.tsx
frontend/src/components/eisenhower/card/DragOverlayCard.tsx
frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/eisenhower/filter/DateRangePicker.tsx
frontend/src/components/ui/calendar.tsx
frontend/src/pages/matrix.tsx
frontend/src/styles/index.css

> ex) #321
스크롤 줄어드면, 버튼 토글 씹힘 현상 (이거 제목 + 텍스트 레이아웃 보관함이랑 동일하게) 이 문제 해결하려면 반응형 레이아웃을 손봐야 할 것 같은데 (보관함과 같은 기준에 md 를 인식하지 않음 반응형 기준이 다름) 좀 오래 걸려서 일단 버튼 씹히는 문제가 심각하니까 임시방편으로 텍스트를 아래로 내려버렷어요 추후 코드 리팩토링 하면서 수정해야 할 것 같습니다

아이젠하워 디자인 QA

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/eisenhower/view/PriorityView.tsx
frontend/src/components/ui/Modal/NodeTaskModal.tsx
frontend/src/pages/brainstorming.tsx

[FE] feat: 아이젠하워 모바일 카드 이동

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/eisenhower/view/PriorityView.tsx

아이젠하워 모바일 대응

---

frontend/src/components/eisenhower/TaskModal.tsx
frontend/src/components/eisenhower/view/CompletedView.tsx
frontend/src/components/eisenhower/view/PriorityView.tsx
frontend/src/components/ui/Modal/WithdrawalModal.tsx
frontend/src/components/ui/chart/DailyCompletionChart.tsx
frontend/src/components/ui/sidebar/BottomBar.tsx
frontend/src/hooks/useAuthRedirect.ts
frontend/src/hooks/useDebounceMindmapUpdate.ts
frontend/src/pages/brainstorming.tsx
frontend/src/pages/mindmap.tsx
frontend/src/pages/pomodoro.tsx
frontend/src/services/authService.ts
frontend/src/store/pomodoro.ts

resolve #326 
- 하단바 active 로직 수정
- 쓸데없는 console.log 수정

[FE] qa: 하단바 active 버그 수정

---

frontend/src/api/endpoints.ts
frontend/src/components/ui/Modal/WithdrawalModal.tsx
frontend/src/components/ui/header/Header.tsx
frontend/src/components/ui/header/NotificationCard.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/hooks/queries/eisenhower/useGetNotification.ts
frontend/src/hooks/useWithdrawAuth.ts
frontend/src/services/eisenhowerService.ts
frontend/src/types/api/eisenhower/response.ts
frontend/src/types/task.ts

resolve #328
알림 기능 및 API를 연동했습니다.
알림 관련 컴포넌트 NotificationCard 를 활용하여 알림 UI를 보여줍니다! 
shadcn/ui 튤팁 컴포넌트를 활용해서 처리했습니다.
알림은 12시 기준으로만 데이터가 바뀌기 때문에, 날짜 기반으로 쿼리를 캐싱해놓고 staleTime을 이에 맞게 설정했습니다!
회원탈퇴 Hot issue가 있어서 급하게 해당 PR과 같이 수정하였습니다!

[FE] feat: 알림 기능 구현

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/ui/Modal/EisenhowerAi.tsx
frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts

> ex) #262
- AI 사분면 추천 시 api 가 모달이 열릴 때를 판단하여 호출하도록 수정했습니다.
- 모바일 드래그앤드롭이 안 되는 문제를 해결하기 위해 delay 등의 값을 수정하였습니다. 이 pr 머지하고 테스트해본 후 다시 문제가 생기면 새로운 이슈 파서 고치도록 하겠습니다.

AI 사분면 추천 오류 및 드래그앤드롭 오류 해결

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/ui/Modal/EisenhowerAi.tsx
frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts

Reverts kookmin-sw/capstone-2025-25#342

Revert "Revert "AI 사분면 추천 오류 및 드래그앤드롭 오류 해결""

---

backend/src/main/java/capstone/backend/domain/todayTask/scheduler/TodayTaskAnalysisScheduler.java

Closes #335 
> 기존 오류가 나던 오늘의 할 일 작업을 수정하였습니다.

[BE] feat: 오늘의 할 일 분석 저장

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/eisenhower/view/PriorityView.tsx
frontend/src/components/ui/Modal/EisenhowerAi.tsx
frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts
frontend/src/hooks/useTaskDnD.ts
frontend/src/pages/login.tsx
frontend/src/pages/matrix.tsx
frontend/src/styles/index.css

> ex) #346
- 우선순위 추천 후 사분면에 바로 적용되지 않는 문제 해결
- 아이젠하워 우선순위 추천 모달 아이콘 수정
- 모바일 드래그앤드롭 시 스크롤 방지
- 드래그앤드롭 시 최적화

아이젠하워 버그 수정

---

backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerNotificationService.java

- Closes #337 
- 아이젠하워 작업 알림 마감일이 하루 남았을때 생성하도록 수정
스케쥴러 10초마다 동작하도록 하고 테스트해본 결과입니다!!
>

[BE] refactor: 아이젠하워 알림 기능 dueDate가 하루 남은 일정 반환으로 수정 

---

frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/brainstorming.tsx

#366
레이아웃 수정
브레인스토밍 input 수정
>

[FE] feat: 레이아웃 수정

---

frontend/src/pages/callback.tsx
frontend/src/routes.ts
frontend/src/services/authService.ts

resolve #368
튜토리얼 페이지 리다이렉트 문제를 수정했습니다.
기존에 온보딩 튜토리얼 페이지가 AuthLayout에 들어있어서 리다이렉트되는 문제가 있어, layout이 없는 별도의 라우트로 지정하였습니다.

[fix]: 튜토리얼 페이지 리다이렉트 문제 수정
