gpt/models/request.py
gpt/routes/gpt.py

> #14 
> 노드 생성 API, 마인드맵 리스트화 API 개선 및 노드 요약 API 추가
- 마인드맵 데이터 구조 최적화
- 부모-자식 관계를 고려한 트리 구조 생성 (build_mindmap_tree)
- GPT 입력을 위한 계층형 텍스트 변환 (format_tree_for_gpt)
- 일정 및 생각 리스트화 API 수정
- convert_schedule_todo: 마인드맵을 기반으로 실행 가능한 TODO 리스트 변환
- convert_thought_list: 핵심 내용을 Key-Value 형태의 리스트로 변환
- 요약 API (summarize_node) 추가
- 주어진 질문과 답변을 기반으로 한 문장 요약 기능 추가
- 마인드맵 및 GPT request 모델 수정
- GPTRequest: 마인드맵 노드 요약을 위한 구조 개선
- MindMapRequest: 일정 및 생각 정리를 위한 마인드맵 데이터 구조 정의
- NodeSummaryRequest: 질문과 답변을 받아 요약을 생성하는 모델 추가
>

GPT API 리팩토링 및 Request/Response 구조 수정

---

backend/src/main/java/capstone/backend/domain/member/controller/MemberController.java
backend/src/main/java/capstone/backend/domain/member/dto/response/UserDataDTO.java
backend/src/main/java/capstone/backend/domain/member/service/MemberService.java

- #104 
1. 상단바에 들어갈 user data를 조회하는 과정이 없음
2. 임시 토큰 발급 후 해당 토큰으로 JWT 발급 받는 api 호출 과정에서 **user data를 조회한 후 zustand에 전역 상태로 저장하는 로직** 필요

[BE] feat: 상단바에 들어갈 유저 데이터 조회 API 작성

---

frontend/src/components/reactFlow/FlowWrapper.tsx
frontend/src/components/reactFlow/nodes/ui/QuestionListNode.tsx
frontend/src/store/mindMapStore.ts

resolve #59 
질문 선택 노드 또는 질문 답변 작성 노드 상태에서 외부(배경) 클릭 시 이전 상태로 되돌리는 기능을 구현했습니다.
`mindMapStore`에 아래 구조에 해당하는 상태를 도입했습니다.
```
type ActiveState = {
nodeId: string;
previousNodes: MindMapNode[];
previousEdges: MindMapEdge[];
previousActiveState: ActiveState | null; // 이전 상태 추적을 위한 계층 추가
};
```
- 여러 단계의 상태 변경을 추적할 수 있는 계층형 구조 구현
- 연결 리스트 형태로 상태 이력을 저장하여 연속적인 상태 복원 가능
새 노드 생성 또는 노드 타입이 변경될 때 마다 이전 상태를 저장하는 로직을 적용했습니다. (`addChildNode`, `setNode`)
React Flow의 `onPaneClick` 메소드를 활용했습니다.
그런데, 드래그앤 드롭을 해서 놔도 `onPaneClick` 이벤트가 발생해서, `onConnectEnd`의 이벤트와 겹치지 않도록 `ignoreNextPaneClick` ref로 pane만 클릭을 감지하도록 처리했습니다.

[FE] feat: 마인드맵 Pane 클릭 시, 노드 상태 복원 기능 구현

---

frontend/src/components/ui/SubSidebarAccordion.tsx
frontend/src/components/ui/header/Header.tsx
frontend/src/components/ui/pomodoro/PomodoroItem.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/CommonSubSidebarWrapper.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapAddButton.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapSubSidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/pomodoro/PomodoroSubSidebar.tsx
frontend/src/styles/index.css

#114 
사이드바 크기 수정, 서브사이드바, item 통일, 스크롤바 제거 및 블러 추가, 헤더 크기 수정 등
헤더, 사이드바, 서브사이드바, item에 대한 스타일을 수정했습니다.
구조상으로 크게 달라진 것은 없습니다.
마인드맵 item에 badge 컴포넌트로 적용해두었습니다!
다른 페이지 수정 필요 사항은 정리해서 곧 공유해드리도록 하겠습니다 :)

[FE] style: 헤더, 사이드바, 서브 사이드바 스타일 수정

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Input.tsx
frontend/src/components/ui/Modal/AddPomodoro.tsx
frontend/src/components/ui/Modal/DeletePomodoro.tsx
frontend/src/components/ui/Modal/EndPomodoro.tsx
frontend/src/components/ui/MultiSlider.tsx
frontend/src/components/ui/SubSidebarAccordion.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/header/Header.tsx
frontend/src/components/ui/pomodoro/PomodoroItem.tsx
frontend/src/components/ui/pomodoro/PomodoroResult.tsx
frontend/src/components/ui/pomodoro/PomodoroTimer.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/CommonSubSidebarWrapper.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapAddButton.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapSubSidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/pomodoro/PomodoroSubSidebar.tsx
frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/pomodoro.tsx
frontend/src/styles/index.css

#115 
뽀모도로 페이지 (결과, 진행), 뽀모도로 모달 (생성, 삭제, 완료) 스타일링 수정했습니다.
- Dialog 전체 레이아웃 , 폰트 사이즈 수정
- Input active 상태 border 수정
- MultiSlider 숫자 버림 처리
- Button 사이즈 조절 (sm, lg), disable color 변경
- TaskCard가 여기저기 동작없이 쓰이는 경우가 많아서 inactive variant로 하나 만들면 좋을 것 같습니다! 우선은 그냥 hover 스타일링 삭제해서 쓸 수 있도록 했는데 아이젠하워 수정하면서 구현되면 고쳐주세요!
- 사이드바 이슈랑 분리해서 작업했는데 push 하면서 섞여 들어간 것 같아요ㅠ! 충돌 날 수도...
- 색상 코드가 잘 못된건지 코드로 적혀있는데 디자인이랑 색상이 다르더라고요 확인 한번하고 나중에 정리해야 할 듯

[FE] style: 뽀모도로 관련 페이지, 모달 스타일링 수정

---

frontend/index.html
frontend/src/components/ui/MultiSlider.tsx
frontend/src/components/ui/SubSidebarAccordion.tsx
frontend/src/components/ui/pomodoro/PomodoroItem.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/SubSidebar.tsx
frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
frontend/src/pages/home.tsx
frontend/src/pages/matrix.tsx
frontend/src/pages/register.tsx
frontend/src/store/sidebarStore.ts

서브사이드바 관련 & 추가 수정사항 반영

---

gpt/main.py
gpt/models/request.py
gpt/models/response.py
gpt/routes/gpt_router.py

- Closes #151 
- 기존 Request, Response에 대한 Swagger에서 표시되는 추가설명 작성
- 입력값 검증을 Request 클래스 들에서 각각 담당하도록 코드 리팩터링
- root 경로로 접근시 /docs 경로로 redirect 시키는 코드 작성
- 보다 편한 Swagger 접근을 위함
>

[BE] refactor: GPT API 예외 처리 및 문서화 작업

---

backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
backend/src/main/java/capstone/backend/domain/member/controller/MemberController.java
backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
backend/src/main/java/capstone/backend/domain/pomodoro/controller/DailyPomodoroSummaryController.java
backend/src/main/java/capstone/backend/domain/pomodoro/controller/PomodoroController.java
backend/src/main/java/capstone/backend/global/swagger/SwaggerConfig.java

- Closes #161 
1. `Swagger-ui.html`에서 보여지는 **App name** 및 **description** 변경
2. 버전 1.0 -> 1.0.0으로 수정
3. 각 컨트롤러 별 네이밍 정보 수정
4. `DailyPomodoroController.java`에서 `@ModelAttribute`로 인해 사용하지 않는 `@Validated` 어노테이션 제거
>

[BE] fix: swagger config 설정 변경 및 컨트롤러 네이밍 설정

---

backend/src/main/java/capstone/backend/domain/eisenhower/exception/MindMapNotLinkedToEisenhowerException.java
backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerItemService.java
backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
backend/src/main/java/capstone/backend/domain/mindmap/dto/request/MindMapRequest.java
backend/src/main/java/capstone/backend/domain/mindmap/dto/request/UpdateMindMapRequest.java
backend/src/main/java/capstone/backend/domain/mindmap/entity/MindMap.java
backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java

- Closes #158 
- 마인드맵 수정 요청 시, nodes / edges 구조만 받아서 업데이트할 수 있도록 했습니다.
- 아이젠하워로 노드 추출 시, 마인드맵과 연관된 아이젠하워가 존재할 경우 아이젠하워의 카테고리를 가져와 적용할 수 있도록 했습니다.

feat: 마인드맵 수정 요청 시 Req body 변경 및 카테고리 조회

---

backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
backend/src/main/java/capstone/backend/global/security/jwt/JwtAuthenticationFilter.java

- Closes #166 
https 적용으로 인한 쿠키 Samesite 및 secure 설정
- https에서는 samesite = None, secure = true 설정 필요
- 크롬 브라우저 쿠키 디폴트 값이 samesite = Lax로 변경됨. (따라서, 설정이 필요함)

[BE] fix: HTTPS 적용으로 인한 cookie 설정 변경

---

backend/src/main/java/capstone/backend/domain/pomodoro/controller/v1/PomodoroV1Controller.java
backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/DailyPomodoroSummaryController.java
backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/PomodoroV2Controller.java
backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java

- Closes #170 
사용하지 않는 controller v1으로 분기 & 기획 수정 이후 사용하는 controller를 v2로 분기
수정된 기획으로 만들어진 것도 다 v2로 할 건지, 버블 같이 이번에 새로 만들어진 도메인은 v1으로 둘 건지 어떻게 하면 좋을까요?
더 수정될 수 있으니 머지는 최종 정해지면 두 분 리뷰 받고 제가 하겠습니다!

[BE] fix: 사용하지 않는 controller v1으로 분기 & 기획 수정 이후 사용하는 controller를 v2로 분기

---

backend/build.gradle
backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
backend/src/main/java/capstone/backend/domain/bubble/dto/request/ConfirmBubbleRequest.java
backend/src/main/java/capstone/backend/domain/bubble/dto/request/PromptRequest.java
backend/src/main/java/capstone/backend/domain/bubble/dto/response/BubbleDTO.java
backend/src/main/java/capstone/backend/domain/bubble/dto/response/PromptResponse.java
backend/src/main/java/capstone/backend/domain/bubble/entity/Bubble.java
backend/src/main/java/capstone/backend/domain/bubble/exception/BubbleNotFoundException.java
backend/src/main/java/capstone/backend/domain/bubble/repository/BubbleRepository.java
backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java
backend/src/main/java/capstone/backend/domain/bubble/service/WebFluxService.java
backend/src/main/java/capstone/backend/domain/member/service/MemberService.java
backend/src/main/java/capstone/backend/global/api/webflux/WebFluxConfig.java
backend/src/main/java/capstone/backend/global/database/querydsl/QuerydslConfig.java
backend/src/main/java/capstone/backend/global/database/redis/RedisConfig.java
backend/src/main/java/capstone/backend/global/security/SecurityConfig.java

- Closes #172 
1. 프롬프트 입력 시 청크 단위로 버블 생성 로직 구현 (비동기 -> 동기 처리로 변경)
2. WebFlux 호출 설정 코드 작성
3. global 레이어에 있는 Database 코드 변경
4. 버블 삭제 로직 구현
5. 버블 확정 로직 구현
- 버블 생성
현재 **버블 확정 시 보관함으로 빼는 로직**이 작성되지 않았습니다.
따라서, 보관함 feature 브랜치 먼저 병합 후 로직 수정 진행하겠습니다.

[BE] feat: Bubble 도메인 관련 API 설계

---

backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerCategoryController.java
backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerItemController.java
backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerNotificationController.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemCreateRequest.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemFilterRequest.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemUpdateRequest.java
backend/src/main/java/capstone/backend/domain/eisenhower/dto/response/EisenhowerItemResponse.java
backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepositoryImpl.java
backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerItemService.java
backend/src/main/java/capstone/backend/domain/mindmap/dto/response/SidebarMindMapResponse.java
backend/src/main/java/capstone/backend/domain/mindmap/repository/MindMapRepository.java
backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/DailyPomodoroSummaryController.java
backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/PomodoroV2Controller.java
backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/SidebarPomodoroResponse.java
backend/src/main/java/capstone/backend/domain/pomodoro/repository/PomodoroRepository.java
backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
backend/src/main/java/capstone/backend/global/swagger/SwaggerConfig.java

- Closes #191 
- 아이젠하워 엔티티 변경
- 내TaskType 필드 삭제
- 마인드맵 연관관계 삭제
- 뽀모도로 연관관계 삭제
- 엔티티 변경에 따른 코드 주석 처리 및 삭제
- 스웨거 설정 변경 
- 서비스명 변경
- 아이젠하워 관련 API 버전 관리를 위한 변경 작업
>

[BE] refactor: 아이젠하워 관련 기능 수정 사항 반영

---

backend/src/main/java/capstone/backend/domain/todayTask/controller/TodayTaskItemController.java
backend/src/main/java/capstone/backend/domain/todayTask/dto/request/TodayTaskItemCreateRequest.java
backend/src/main/java/capstone/backend/domain/todayTask/dto/response/TodayTaskItemResponse.java
backend/src/main/java/capstone/backend/domain/todayTask/entity/TodayTaskItem.java
backend/src/main/java/capstone/backend/domain/todayTask/exception/TodayTaskNotFoundException.java
backend/src/main/java/capstone/backend/domain/todayTask/repository/TodayTaskItemRepository.java
backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskItemService.java

- Closes #182 
- 전체 조회 API
- 삭제 API 
- 생성 API
- 오늘 해야 할 일 총 개수
- 오늘 해야 할 일 중 완료한 개수
- 어제 해야 할 일 조회
- 어제 일 오늘로 날짜 변경
> 해야 할 일은 항상 오늘 날짜로 생성됩니다. 테스트를 위해 어제 날짜꺼로 변경할 수 있도록 구현해놨습니다. 프론트에서도 쓸 것 같아서 놔뒀는데 삭제하는게 나을까요??

[BE] feat: 오늘의 할 일 도메인 관련 API 로직 구현

---

frontend/src/api/endpoints.ts
frontend/src/components/today/TodayList.tsx
frontend/src/components/today/TodayMainDashborad.tsx
frontend/src/components/ui/chart/DailyCompletionChart.tsx
frontend/src/components/ui/chart/TodayCompleteChart.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/hooks/queries/category/useGetCategoryList.ts
frontend/src/hooks/queries/today/useGetTodayTodoCompletedCount.ts
frontend/src/hooks/queries/today/useGetTodayTodoCount.ts
frontend/src/hooks/queries/today/useGetTodayTodoList.ts
frontend/src/hooks/queries/today/useGetYesterdayTodoList.ts
frontend/src/hooks/queries/today/useMoveToday.ts
frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/home.tsx
frontend/src/pages/today.tsx
frontend/src/services/categoryService.ts
frontend/src/services/todayService.ts
frontend/src/types/api/category/index.ts
frontend/src/types/api/category/response.ts
frontend/src/types/api/today/index.ts
frontend/src/types/api/today/response.ts
frontend/src/types/category.ts
frontend/src/types/todayTodo.ts

resolve #195 
오늘의 할 일 관련 API를 연동했습니다. 
해당 PR에서 변경된 디자인 수정 반영 완료했습니다!
오늘 및 어제의 할 일 리스트 조회 API를 연동하였습니다.
해당 과정 작업 중에 오늘의 할 일 시간 설정으로 인한 API 오류 있었던 부분은 백엔드 팀원 @eraser502 과 소통하여 해결했습니다! 
오늘의 할 일의 총개수와 완료개수를 전달받는 API를 활용하여 그래프 데이터에 보여주도록 처리했습니다. 
category_id 필드로 넘어오는 상황이여서, 카테고리 리스트를 조회하고 텍스트로 변환하는 유틸 함수를 지정하여 처리하였습니다. 
해당 로직은 하루 지났을 때 요청 보내보고 잘 작동하는지 확인해볼 예정입니다! 로직 상에는 문제가 없다고 판단되어 우선 PR 올립니당
++ 응원의 한마디는 임시로 그냥 넣어놨습니다 ㅎㅎ..
현재 차트 및 리마인더 데이터 관련해서는 백엔드에서 개발이 안된 상황이라, 임시 더미데이터로 처리해놨습니다!

오늘의 할 일 API 연동

---

frontend/src/api/endpoints.ts
frontend/src/components/mindmap/MindmapSkeleton.tsx
frontend/src/components/mindmap/MindmapWrapper.tsx
frontend/src/hooks/queries/brainstorming/usePatchBubble.ts
frontend/src/hooks/queries/gpt/useBrainStormingAnalyze.ts
frontend/src/hooks/queries/gpt/useBrainStormingRewrite.ts
frontend/src/pages/brainstorming.tsx
frontend/src/pages/mindmap.tsx
frontend/src/routes.ts
frontend/src/services/brainstormingService.ts
frontend/src/services/gptService.ts
frontend/src/store/mindMapStore.ts
frontend/src/types/api/gpt/index.ts
frontend/src/types/api/gpt/request.ts
frontend/src/types/api/gpt/response.ts

resolve #210 
마인드맵과 브레인스토밍을 연결하면서 필요한 API 작업을 연동했습니다.
url parameter 관련으로 관련 데이터를 넘겨주고, 마인드맵 페이지에서 추천 노드를 뽑아내는 API를 호출합니다.
이때 Pending 상태일 때의 UI를 아래와 같이 컴포넌트로 제작했습니다. 
뭔가 더 좋은 사용자 경험을 제공하기 위해, 실제 마인드맵 노드의 형태에 Skeleton UI를 적용하고자 하는 목표가 있습니다...!! 추후에 발전시킬 계획입니다 😄 
API 호출이 완료된 해당 정보를 바탕으로 초기 마인드맵 데이터를 세팅해줍니다. (아래 사진과 같이)
마인드맵 데이터를 가공하여 한 줄 요약을 뽑아내는 API를 호출합니다.
이때 로딩 상태를 완료 버튼에 Loading Spinner를 적용하였습니다. 
요약을 뽑아내면 모달로 요약된 한 줄의 데이터를 보여줍니다. 
위 모달 사진에서 적용하기 버튼을 누르면 버블 텍스트를 수정하는 API를 호출합니다. 
위의 예시에서 적용을 누르면 브레인스토밍 페이지로 이동하고 아래와 같이 버블의 텍스트가 업데이트됩니다!
내일 급하게 1차적으로 교수님께 시연 + 배포해야하는 사정으로 코드 구조와 사용자 경험 측면에서 좀 더 나은 방향이 있을 것 같은 아쉬움이 있는 상황입니다! 
해당 사항들은 다음주 내로 더 발전시켜 수정하도록 하겠습니다 😄

마인드맵 - 브레인스토밍 연결

---

backend/src/main/java/capstone/backend/domain/eisenhower/batch/NotificationJobConfig.java
backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
backend/src/main/java/capstone/backend/domain/todayTask/batch/SaveTodayTaskAnalysisTasklet.java
backend/src/main/java/capstone/backend/domain/todayTask/batch/TodayTaskAnalysisJobConfig.java
backend/src/main/java/capstone/backend/domain/todayTask/controller/TodayTaskAnalysisController.java
backend/src/main/java/capstone/backend/domain/todayTask/controller/TodayTaskItemController.java
backend/src/main/java/capstone/backend/domain/todayTask/dto/request/TodayTaskItemCreateRequest.java
backend/src/main/java/capstone/backend/domain/todayTask/dto/request/TodayTaskUpdateRequest.java
backend/src/main/java/capstone/backend/domain/todayTask/dto/response/TodayTaskAnalysisResponse.java
backend/src/main/java/capstone/backend/domain/todayTask/entity/DayOfWeekEnum.java
backend/src/main/java/capstone/backend/domain/todayTask/entity/TodayTaskAnalysis.java
backend/src/main/java/capstone/backend/domain/todayTask/entity/TodayTaskItem.java
backend/src/main/java/capstone/backend/domain/todayTask/exception/DuplicateTaskException.java
backend/src/main/java/capstone/backend/domain/todayTask/repository/TodayTaskAnalysisRepository.java
backend/src/main/java/capstone/backend/domain/todayTask/repository/TodayTaskItemRepository.java
backend/src/main/java/capstone/backend/domain/todayTask/scheduler/TodayTaskAnalysisScheduler.java
backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskAnalysisService.java
backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskItemService.java
backend/src/main/java/capstone/backend/global/batch/runner/MultiJobLauncher.java
backend/src/main/java/capstone/backend/global/batch/service/MultiJobExecutionService.java

- Closes #216 
오늘의 할 일
- 오늘의 할 일 페이지에서 체크버튼 누를 경우 상태 변경 구현
- 자정 기준으로 날짜 조회 변경, 예전 코드 삭제
- 할 일 추가 시 기존 리스트로 여러개 추가에서 한개씩 추가로 변경
- 같은 날짜에 동일 사용자가 같은 아이젠하워 아이템을 추가할 수 없도록 제약 조건 설정
오늘의 할 일 분석 
- 오늘 기준으로 어제부터 7일간 데이터 가져오도록 조회 API 구현
- 자정에 분석 데이터 저장 스케줄러 구현
> 오늘의 할 일 분석에서 자정에 데이터 분석 저장 시 배치 처리

[BE] feat: 오늘의 할 일 및 분석 구현

---

frontend/src/components/ui/header/Header.tsx
frontend/src/layouts/DefaultLayout.tsx

> ex) #202
- 토큰이 사라지면 login 으로 이동하도록 `useAuthRedirect` 를 사용하였습니다.
- 로그아웃 버튼 클릭 시 `authService` 의 logout 을 사용하도록 수정하였고 이후 login 페이지로 이동하도록 했습니다.
- refreshToken 로직의 경우, 건 님과 조금 더 테스트 해보는 게 좋을 것 같아 추후 더 반영하도록 하겠습니다.

로그아웃 관련 로직 수정

---

frontend/package-lock.json
frontend/package.json
frontend/src/api/endpoints.ts
frontend/src/components/inventory/InventoryItemCard.tsx
frontend/src/components/today/ReminderList.tsx
frontend/src/components/today/TodayList.tsx
frontend/src/components/today/TodayMainDashborad.tsx
frontend/src/components/ui/brainstorming/MoveToInventoryModal.tsx
frontend/src/components/ui/chart/DailyCompletionChart.tsx
frontend/src/components/ui/sidebar/Sidebar.tsx
frontend/src/components/ui/switch.tsx
frontend/src/hooks/queries/analysis/useGetTodayTaskAnalysis.ts
frontend/src/hooks/queries/inventory/folder/useUpdateFolderName.ts
frontend/src/hooks/queries/inventory/item/useCreateInventoryItem.ts
frontend/src/hooks/queries/inventory/item/useGetRecentInventory.ts
frontend/src/hooks/queries/today/useDeleteTodayTodo.ts
frontend/src/hooks/queries/today/useUpdateStatusTodo.ts
frontend/src/pages/brainstorming.tsx
frontend/src/pages/inventory.tsx
frontend/src/pages/inventoryDetail.tsx
frontend/src/pages/today.tsx
frontend/src/services/analysisService.ts
frontend/src/services/inventoryFolderService.ts
frontend/src/services/inventoryItemService.ts
frontend/src/services/todayService.ts
frontend/src/types/analysis.ts
frontend/src/types/api/analysis/index.ts
frontend/src/types/api/analysis/response.ts
frontend/src/types/api/inventory/item/request.ts
frontend/src/types/api/inventory/item/response.ts

resolve #237 
`브레인스토밍 <-> 보관함 <-> 오늘의 할 일`
위 세 단계의 관련 작업들을 처리했습니다. 
**1. 리마인더 API 연동**
**2. 할 일 완료 및 삭제 기능 추가**
API 요청 성공 시, toast를 뜨도록 처리했습니다! 
**3. 오늘의 할 일 분석 데이터 연동**
이외 레이아웃 관련 CSS 수정 작업도 진행했습니다.
브레인스토밍에서 보관함으로 옮기는 기능 개발했습니다. 모달 UI는 이전에 보관함 폴더 이동 기능 때 활용했던 모달을 재활용하여 구현했습니다.
그런데 보관함 이동 API 요청 시, 브레인스토밍 리스트에 해당 아이템이 삭제 반영 안 되고 있어서 해당 부분 백엔드에 수정 요청한 상태입니다.
**폴더명 수정 기능 개발**
수정 아이콘 눌렀을 시, 폴더명을 input으로 변경하여 편집모드 UI를 구현하였습니다.
이때 편집 중인 상태면, 다른 리스트를 눌러도 이동은 못하도록 막아놨습니다! 
현재 뽀모도로 관련 데이터 API가 아직 개발되지 않아서, 해당 부분은 전달 받는대로 바로 적용할 예정입니다!

[FE]: 브레인스토밍 <-> 보관함 <-> 오늘의 할 일 관련 작업 처리

---

backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryItemController.java
backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java

- Closes #249 
- 뽀모도로 완료 및 기록 로직 확정으로 인한 주석 제거
- 보관함 아이템 생성 중복 API 제거
>

[BE] hotfix: 보관함 아이템 생성 중복 API 제거

---

frontend/src/components/mindmap/CustomNode.tsx
frontend/src/components/mindmap/MindmapSkeleton.tsx
frontend/src/components/mindmap/MindmapWrapper.tsx
frontend/src/layouts/DefaultLayout.tsx
frontend/src/pages/mindmap.tsx
frontend/src/store/mindMapStore.ts
frontend/src/styles/index.css

resolve #270 
- 백스페이스하면 날라감
- 오른쪽 맨 위에 노드 내부 → 삭제
- 메인노드 수정+삭제 안되도록
- 마인드맵 페이지 벗어나면 경고창 (현재 페이지를 벗어나면 마인드맵은 저장되지 않는다)
- 브레인스토밍 화면처럼 전체 영역 배경 !!
- 빈 텍스트 있을 때 API 요청 안되도록!
- 오른쪽 아래 React Flow 버튼 안 보이게!!

[FE] qa: 마인드맵 수정사항 반영

---

backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemCreateRequest.java
backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemUpdateRequest.java
backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryFolder.java
backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryItem.java
backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryFolderRepository.java
backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryItemRepository.java
backend/src/main/java/capstone/backend/domain/inventory/service/InventoryFolderService.java
backend/src/main/java/capstone/backend/domain/inventory/service/InventoryItemService.java

Closes #284 
- 보관함 아이템 생성 시 제목의 글자 수 20글자 제한을 걸지 않도록 수정했습니다.
- 보관함 폴더 속, 아이템 조회 시 orderby createdAt 했습니다.
- 보관함 폴더 조회 시 orderby createdAt 했습니다.

[BE] hotfix: 보관함 수정사항

---

backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/DailyPomodoroSummaryController.java
backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/DailyPomodoroDTO.java
backend/src/main/java/capstone/backend/domain/pomodoro/schema/DailyPomodoroSummary.java
backend/src/main/java/capstone/backend/domain/pomodoro/schema/PomodoroCycle.java
backend/src/main/java/capstone/backend/domain/pomodoro/service/DailyPomodoroSummaryService.java
backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
backend/src/main/java/capstone/backend/domain/pomodoro/util/PomodoroTimeUtils.java

- Closes #293 
FE의 요청사항에 따라 다음과 같은 작업을 수행했습니다.
1. 뽀모도로 타이머 기록에 요일 데이터 추가
2. 한 주 동안의 뽀모도로 기록 로직 : 일주일 전부터 어제까지의 데이터를 조회하는 방식으로 변경
- 지난 주차에 대한 뽀모도로 기록 샘플 데이터 삽입. (오늘자 데이터는 보여주지 않는지 테스트 하기 위해 5/14 데이터도 삽입)
- 금주 뽀모도로 기록 API
@cychann @eraser502 
유찬이 도훈이 컨펌 받고 로직 최종 확정하겠습니다~

[BE] fix: 뽀모도로 타이머 기록 타입 수정

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/mindmap/MindmapWrapper.tsx
frontend/src/components/today/TodayList.tsx
frontend/src/components/today/TodayMainDashborad.tsx
frontend/src/components/ui/chart/DailyCompletionChart.tsx
frontend/src/components/ui/chart/PomodoroCompletionChart.tsx
frontend/src/hooks/queries/category/useGetCategoryList.ts
frontend/src/hooks/queries/today/useCreateTodayTask.ts
frontend/src/pages/mindmap.tsx
frontend/src/store/mindMapStore.ts
frontend/src/types/analysis.ts

[FE] qa 추가 수정 사항

---

backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerCategoryService.java

- Closes #299 
- 아이젠하워 카테고리 삭제 시 연관된 작업의 카테고리 null 처리
>

fix: 아이젠하워 카테고리 삭제 시 연관된 작업의 카테고리 null 처리

---

frontend/src/components/eisenhower/card/TaskCard.tsx
frontend/src/components/ui/Modal/NodeTaskModal.tsx
frontend/src/pages/matrix.tsx
frontend/src/types/api/brainstorming/request.ts

- 카테고리 생성할 때, 실패 모달이 뜨는 점 수정
- 카테고리 생성하면 바로 할당이 되도록 처리
- 브레인스토밍 → 아이젠하워 로 할 일 내보내는 요청 제대로 값 안 들어가는 문제 수정

카테고리 기능 관련 QA

---

backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
backend/src/main/java/capstone/backend/domain/bubble/dto/request/MergeBubbleRequest.java
backend/src/main/java/capstone/backend/domain/bubble/repository/BubbleRepository.java
backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java

Closes #357 
버블을 합치는 API를 만들었습니다.
req로 병합할 버블 list와 제목을 받으면, 해당 list의 버블들을 모두 삭제하고, 새로운 버블을 생성하도록 구현했습니다.
버블 생성 시 아래와 같이 코드를 작성하여 member에 대한 조회가 2번 일어나지 않도록 했습니다.
`Bubble newBubble = Bubble.create(request.mergedTitle(), bubblesToDelete.get(0).getMember());`

[BE] feat: 버블 병합 API 구현

---

backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
backend/src/main/java/capstone/backend/domain/auth/dto/response/AccessTokenResponse.java
backend/src/main/java/capstone/backend/domain/auth/dto/response/TokenResponse.java
backend/src/main/java/capstone/backend/domain/auth/service/AuthService.java
backend/src/main/java/capstone/backend/domain/member/controller/MemberController.java
backend/src/main/java/capstone/backend/domain/member/scheme/Member.java
backend/src/main/java/capstone/backend/domain/member/service/MemberService.java
backend/src/main/java/capstone/backend/global/security/oauth2/service/CustomOAuth2UserService.java

- Closes #351 
Member 엔티티 내부에 isRegistered 컬럼을 생성하여, 최초/재 로그인 판별을 위한 필드를 추가하였습니다.
이후 CustomOAuthUserService에서 첫 소셜 로그인 시도 시 false로 생성하게 하였고, 두 번째 소셜 로그인 시도 시 true로 변경하는 로직을 구축하였습니다.
이후 FE의 요청에 따라 JWT를 발급하는 과정에서 isRegistered 데이터를 같이 보내주는 것으로 처리하였습니다.
현재, 두 번째 소셜 로그인 시도 이후부터 isRegistered를 true로 설정하는 로직이 실행됩니다.
하지만 사용자가 튜토리얼 페이지를 거치지 않고 카카오 로그인을 순간적으로 두 번 요청해버리는 순간, isRegistered가 바로 true가 되지 않을까 하는 생각이 듭니다.
따라서, 튜토리얼 페이지를 거치는 경우에 BE에서 isRegistered를 true로 변경하는 API를 생성한 뒤, 이를 FE에서 호출하는 방식으로 가야할 지, 지금 구현된 방식으로 가야 할 지 고민입니다...

[BE] feat: 최초 로그인 / 재로그인 분기 처리
